### ISSUE TITLE
Generative Sequencer - Gate/trigger whenever a sequence changes

### ISSUE THREAD

**Issue by benjiao** [awonak/HagiwoModulove#6]
I don't find myself using the constant voltage output much, so this might be a better way to use the extra outputs of the Sync LFO instead? That's just me, though. :smile:

**Comment by awonak** [comment]
I find myself wanting this feature too! Unfortunately this change requires a hardware change, so I'm going to mark this as out of scope for this repo. I'll keep this in mind for similar firmware on hardware that supports it.
