### ISSUE TITLE
Certainty - Use reset input to advance/randomize seed?

### ISSUE THREAD

**Issue by benjiao** [awonak/HagiwoModulove#7]
Should be useful for unattended jams

**Comment by awonak** [comment]
Linus had that same suggestion. After jamming with the firmware a bit, I totally agree. I think using RST to reseed is much more useful than resetting the sequence.

**Comment by benjiao** [comment]
But maybe leave the sequence length the same, right?

**Comment by awonak** [comment]
Fixed in a18e5b0178f0a5316d5966c736ec252cd5c3c050!
